version: 1.0.{build}

os:
  - Visual Studio 2015

build_script:
  - waf configure --check-cxx-compiler msvc --msvc_lazy_autodetect
  - waf clean build --notests

test_script:
  - waf build --alltests
